Counter=9

[Command_0]
Command=cycle-values loop-file "inf" "no"
Order=1
OsdMessage=Loop: ${loop-file}
Type=shortcut

[Command_6]
Command=set include "/home/kilian/.config/mpv/mpv.conf"
Order=2
OsdMessage=
SetOnStartup=false
Type=startup

[Command_7]
Command=set sub-ass-style-override force
Order=0
OsdMessage=
SetOnStartup=true
Type=startup

[Command_8]
Command=set sub-ass-override yes\nset sub-ass-style-override force
Order=3
OsdMessage=
SetOnStartup=false
Type=startup
