[Audio]
ReplayGainFallback=12
ReplayGainPreamp=3
Volume=35

[General]
ColorScheme=Default
FloatingFooterTrigger=BottomMouseMovement
LastPlayedFile=file:///mnt/shared/Handbraked/kathy_147_whoiswale_whatpeachy_2026-06-12_doggy_dildo_MQ_FS_.mkv
PreviewThumbnailWidth=300
RememberWindowGeometry=true
ShowHeader=false
ShowMenuBar=false
ShowPreviewThumbnail=true

[Mouse]
Back=seekPreviousChapterAction
Backx2=playPreviousAction
Forward=seekNextChapterAction
Forwardx2=playNextAction

[Playback]
RestoreFilePosition=true

[Playlist]
PlaybackBehavior=StopAfterItem
PlaylistWidth=525.1484375
Position=left
Style=withThumbnails

[Subtitles]
FontFamily=Serif
FontSize=57
PreferredLanguage=eng

[Video]
ScreenshotFormat=webp
