[Audio]
ReplayGainFallback=12
ReplayGainPreamp=3
Volume=45

[General]
ColorScheme=Default
FloatingFooterTrigger=BottomMouseMovement
LastPlayedFile=file:///mnt/laptop/Videos/kloeking_/kloeking__2026-08-14_03-47-59_343.mts
PreviewThumbnailWidth=300
RememberWindowGeometry=true
ShowHeader=false
ShowMenuBar=false
ShowPreviewThumbnail=true

[Mouse]
Back=seekPreviousChapterAction
Backx2=playPreviousAction
Forward=seekNextChapterAction
Forwardx2=playNextAction

[Playback]
RestoreFilePosition=true

[Playlist]
PlaybackBehavior=StopAfterItem
PlaylistWidth=470.1875
Position=left
Style=withThumbnails

[Subtitles]
FontFamily=Serif
FontSize=57
PreferredLanguage=eng

[Video]
ScreenshotFormat=webp
