[Audio]
ReplayGainFallback=12
ReplayGainPreamp=3
Volume=35

[General]
ColorScheme=Default
FloatingFooterTrigger=BottomMouseMovement
LastPlayedFile=file:///home/killian/Videos/2a37d72549933a84d9b88e7387368bff.mkv
PreviewThumbnailWidth=300
RememberWindowGeometry=true
ShowHeader=false
ShowMenuBar=false
ShowPreviewThumbnail=true

[Mouse]
Back=seekPreviousChapterAction
Backx2=playPreviousAction
Forward=seekNextChapterAction
Forwardx2=playNextAction

[Playback]
RestoreFilePosition=true

[Playlist]
PlaybackBehavior=StopAfterItem
PlaylistWidth=448.17325367647055
Position=left
Style=withThumbnails

[Subtitles]
FontFamily=Serif
FontSize=57
PreferredLanguage=eng

[Video]
ScreenshotFormat=webp
