RIGHT seek 5
LEFT seek -5
UP seek 30
DOWN seek -30
SHIFT+RIGHT seek 15
SHIFT+LEFT seek -15
PGUP add chapter 1
PGDWN add chapter -1
Ctrl+RIGHT sub-seek 1
Ctrl+LEFT sub-seek -1
SPACE cycle pause
. frame-step
, frame-back-step
> playlist-next
< playlist-prev
F5 seek 0 absolute
Ctrl+q quit
ESC set fullscreen no
STOP stop
] add speed 0.1
[ add speed -0.1
BS set speed 1
m cycle mute
9 add volume 5
0 add volume -5
WHEEL_UP add volume 5
WHEEL_DOWN add volume -5
# cycle audio
@ cycle audio down
j cycle sub
J cycle sub down
z add sub-delay -0.1
Z add sub-delay 0.1
Ctrl+s cycle sub-visibility
Ctrl+z add sub-scale 0.1
Ctrl+x add sub-scale -0.1
R add sub-pos +1
l ab-loop
r cycle-values loop-file inf no
} add audio-delay 0.1
{ add audio-delay -0.1
1 add contrast 1
2 add contrast -1
Ctrl+1 set contrast 0
3 add brightness 1
4 add brightness -1
Ctrl+3 set brightness 0
5 add gamma 1
6 add gamma -1
Ctrl+5 set gamma 0
7 add saturation 1
8 add saturation -1
Ctrl+7 set saturation 0
Ctrl+r cycle-values video-rotate 90 180 270 0
Ctrl+e cycle-values video-rotate 270 180 90 0
Ctrl++ add video-zoom 0.1
Ctrl+- add video-zoom -0.1
Ctrl+0 set video-zoom 0
Ctrl+Alt+LEFT add video-pan-x -0.01
Ctrl+Alt+RIGHT add video-pan-x 0.01
Ctrl+Alt+UP add video-pan-y -0.01
Ctrl+Alt+DOWN add video-pan-y 0.01
d cycle deinterlace
s screenshot
