#!/usr/bin/env bash

# Get installed packages for fast awk lookup
installed_file=$(mktemp)
pacman -Qq 2>/dev/null | sort -u >"$installed_file"

cleanup() { rm -f "$installed_file"; }
trap cleanup EXIT

fzf_args=(
  --multi
  --preview 'pacman -Sii {2}'
  --preview-label='alt-p: toggle preview | alt-j/k: scroll preview | tab: multi-select'
  --preview-label-pos='bottom'
  --preview-window 'down:65%:wrap'
  --bind 'alt-p:toggle-preview'
  --bind 'alt-d:preview-half-page-down,alt-u:preview-half-page-up'
  --bind 'alt-k:preview-up,alt-j:preview-down'
  --color 'pointer:green,marker:green'
  --bind 'ctrl-j:down,ctrl-k:up'
)

pkg_names=$(
  pacman -Slq |
    awk -v installed="$installed_file" '
      BEGIN { while (getline < installed) pkgs[$1]=1 }
      !seen[$1]++ {
        if ($1 in pkgs) printf "★ %s\n", $1; else printf "○ %s\n", $1
      }
    ' |
    fzf "${fzf_args[@]}" |
    awk '{print $2}'
)

if [ -n "$pkg_names" ]; then
  echo "$pkg_names" | tr '\n' ' ' | xargs paru -S --noconfirm
fi
